            - name: Deploy to Neocities using Ruby CLI
  # You may pin to the exact commit or the version.
  # uses: jonchang/deploy-neocities@fb729c428dc0bb4d995de51f462ffcbeb06824a1
  uses: jonchang/deploy-neocities@v2
  with:
    # Neocities API token
    key: 
    # Local directory to deploy
    dir: wrens-webhome
    # Also delete remote files that don't exist locally
    clean: # optional
          
